### ISSUE TITLE
微信扫码登录时，提示报错OperationProcessingError: "response" content-type must be application/json

### ISSUE THREAD

**Issue by jihaobin** [liuhuapiaoyuan/next-auth-oauth#19]
# 问题描述
我复制了仓库中的wechat provider到我的项目中，然后使用了它，但是不知道什么原因，导致AuthJS显示如下报错
[auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: OperationProcessingError: "response" content-type must be application/json
    at OPE (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\node_modules__pnpm_f5d94d._.js:1776:12)
    at notJson (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\node_modules__pnpm_f5d94d._.js:1943:12)
    at assertContentType (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\node_modules__pnpm_f5d94d._.js:1952:15)
    at assertApplicationJson (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\node_modules__pnpm_f5d94d._.js:1931:5)
    at processGenericAccessTokenResponse (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\node_modules__pnpm_f5d94d._.js:2865:5)
    at processAuthorizationCodeOAuth2Response (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\node_modules__pnpm_f5d94d._.js:3119:26)
    at Module.processAuthorizationCodeResponse (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\node_modules__pnpm_f5d94d._.js:3059:12)
    at handleOAuth (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\4a859_@auth_core_3d77d4._.js:3415:243)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.callback (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\4a859_@auth_core_3d77d4._.js:3864:41)
    at async AuthInternal (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\4a859_@auth_core_3d77d4._.js:4941:24)
    at async Auth (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\4a859_@auth_core_3d77d4._.js:5202:34)
    at async GET (C:\Users\admin\Desktop\next-example\next-auth-example\.next\server\chunks\[root of the server]__c1070d._.js:748:26)
    at async AppRouteRouteModule.do (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:10:32804)
    at async AppRouteRouteModule.handle (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:10:39698)
    at async doRender (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\base-server.js:1452:42)
    at async responseGenerator (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\base-server.js:1813:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\base-server.js:1823:28)
    at async DevServer.renderPageComponent (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\base-server.js:2250:24)  
    at async DevServer.renderToResponseImpl (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\base-server.js:2288:32) 
    at async DevServer.pipeImpl (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\base-server.js:959:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\next-server.js:281:17)
    at async DevServer.handleRequestImpl (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\base-server.js:853:17)     
    at async C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\dev\next-dev-server.js:371:20
    at async Span.traceAsyncFn (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\trace\trace.js:153:20)
    at async DevServer.handleRequest (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\dev\next-dev-server.js:368:24) 
    at async invokeRender (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\lib\router-server.js:230:21)
    at async handleRequest (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\lib\router-server.js:408:24)
    at async requestHandlerImpl (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\lib\router-server.js:432:13)        
    at async Server.requestListener (C:\Users\admin\Desktop\next-example\next-auth-example\node_modules\.pnpm\next@15.1.0_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\server\lib\start-server.js:146:13) 

# auth.ts代码
```typescript
export const { handlers, auth, signIn, signOut } = NextAuth(() => {
  const adapter = DrizzleAdapter(db);

  return {
    pages: {
      signIn: "/auth/login",
    },
    adapter: adapter,
    providers: [
      GitHub({
        allowDangerousEmailAccountLinking: true,
      }),
      Google({
        authorization: {
          params: {
            prompt: "consent",
            access_type: "offline",
            response_type: "code",
          },
        },
        allowDangerousEmailAccountLinking: true,
      }),
      CredentialsProvider({
        authorize: async (credentials) => {
          const { email, password } = credentials as loginFormSchemaType;

          if (!email || !password) {
            return null;
          }

          const user = await db.query.users.findFirst({
            where: (user, { eq }) => eq(user.email, email),
          });

          if (!user) return null;

          if (!(await bcrypt.compare(password, user.password))) return null;

          return user;
        },
      }),
      WeChat,
    ],
  };
});
```
# 点击微信登录按钮的方法
```typescript
export async function login(provider: string, redirect_to: string) {
  await signIn(provider, { redirectTo: redirect_to });
}

export async function loginWithGithub() {
  await login("github", "/user");
}
export async function loginWithGoogle() {
  await login("google", "/user");
}

export async function loginWithWechat() {
  await login("wechat", "/user");
}
```
# 操作步骤
## 第一步
我点击了这个按钮
![image](https://github.com/user-attachments/assets/2ccf44b6-7603-420a-b942-63c5be2686be)
## 第二步
之后跳转到了扫码的页面
![image](https://github.com/user-attachments/assets/387dfd87-28ec-4377-bf0f-8fdc21121a66)
## 第三步
扫码之后，跳转到了默认的错误页面，并且控制台出现上面提到的错误信息
![image](https://github.com/user-attachments/assets/2e590809-eaff-4d4a-86e9-c504c9e230e9)

这个问题已经困扰了我很长的时间，我甚至不知道如何对这个错误进行调试，我也无法得知微信给我返回了什么错误信息，希望你能够解答我的问题，谢谢🙏

**Comment by liuhuapiaoyuan** [comment]
抱歉，前几日没注意到，我稍后确认下问题，非常感谢反馈

**Comment by liuhuapiaoyuan** [comment]
**很抱歉，我测试后是可以正常登录了，无法复现您的问题。**
您可以尝试debug下面这个代码看下返回信息是什么
![image](https://github.com/user-attachments/assets/7df7d782-9047-4331-9e47-1c8d48b986e1)


**对应的是您的报错信息中：**

我复制了仓库中的wechat provider到我的项目中，然后使用了它，但是不知道什么原因，导致AuthJS显示如下报错
[auth][error] CallbackRouteError: Read more at [https://errors.authjs.dev#callbackrouteerror](https://errors.authjs.dev/#callbackrouteerror)
[auth][cause]: OperationProcessingError: "response" content-type must be application/json
at OPE (C:\Users\admin\Desktop\next-example\next-auth-example.next\server\chunks\node_modules__pnpm_f5d94d..js:1776:12)
at notJson (C:\Users\admin\Desktop\next-example\next-auth-example.next\server\chunks\node_modules__pnpm_f5d94d..js:1943:12)
at assertContentType (C:\Users\admin\Desktop\next-example\next-auth-example.next\server\chunks\node_modules__pnpm_f5d94d..js:1952:15)
at assertApplicationJson (C:\Users\admin\Desktop\next-example\next-auth-example.next\server\chunks\node_modules__pnpm_f5d94d..js:1931:5)
> **at processGenericAccessTokenResponse (C:\Users\admin\Desktop\next-example\next-auth-example.next\server\chunks\node_modules__pnpm_f5d94d..js:2865:5)**
at processAuthorizationCodeOAuth2Response (C:\Users\admin\Desktop\next-example\next-auth-example.next\server\chunks\node_modules__pnpm_f5d94d..js:3119:26)
